version: '3.8'

services:
  ros1:
    build:
      context: .
      dockerfile: Dockerfile-ros1
    container_name: ros1_noetic
    environment:
      - ROS_MASTER_URI=http://ros1_noetic:11311
    tty: true

  ros2:
    build:
      context: .
      dockerfile: Dockerfile-ros2
    container_name: ros2_humble
    tty: true

  bridge:
    build:
      context: .
      dockerfile: Dockerfile-bridge
    container_name: ros1_ros2_bridge
    depends_on:
      - ros1
      - ros2
    environment:
      - ROS_MASTER_URI=http://ros1_noetic:11311
    tty: true
