FROM ros:foxy-ros1-bridge-focal

#SHELL ["/bin/bash"]

#ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp
#ENV ROS_DOMAIN_ID=0

CMD ["bash", "-c", "source ros_entrypoint.sh && ros2 run ros1_bridge dynamic_bridge --bridge-all-topics"]
